#!/bin/sh
#
#     SUSE system statup script for Jenkins
#     Copyright (C) 2007  Pascal Bleser
#          
#     This library is free software; you can redistribute it and/or modify it
#     under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation; either version 2.1 of the License, or (at
#     your option) any later version.
#			      
#     This library is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     Lesser General Public License for more details.
#      
#     You should have received a copy of the GNU Lesser General Public
#     License along with this library; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
#     USA.
#
### BEGIN INIT INFO
# Provides:          nexus
# Required-Start:    $local_fs $remote_fs $network $time $named
# Should-Start: $time postfix dovecot
# Required-Stop:     $local_fs $remote_fs $network $time $named
# Should-Stop: $time sendmail
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Sonatype Nexus Repositories
# Description:       Start the Sonatype Nexus Repositories
### END INIT INFO

DIRNAME=/opt/nexus/bin
PROGNAME=`basename "$0"`

usage() {
    echo "${PROGNAME} { console | start | stop | restart | status }"
    exit 1
}

if [ "x$1" == "x" ]; then
    usage
fi

run() {
    case "$1" in
        'console')
            shift
            exec "${DIRNAME}/karaf" "$@"
            ;;
        'start')
            shift
            exec "${DIRNAME}/start" "$@"
            ;;
        'stop')
            shift
            exec "${DIRNAME}/stop" "$@"
            ;;
        'restart')
            shift
            "${DIRNAME}/stop" 2>/dev/null
            exec "${DIRNAME}/start" "$@"
            ;;
        'status')
            shift
            exec "${DIRNAME}/status" "$@"
            ;;
        *)
            usage
            ;;
    esac
}

run "$@"